// <auto-generated />
using System;
using MSMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MSMS.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241120063245_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MSMS.Models.Dashboard.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "",
                            Name = "John Doe",
                            Password = "test123",
                            Role = 0,
                            Username = "c0mplex"
                        },
                        new
                        {
                            Id = 2,
                            Email = "",
                            Name = "Jane Doe",
                            Password = "test123",
                            Role = 3,
                            Username = "test123"
                        });
                });

            modelBuilder.Entity("MSMS.Models.MedicineInventory.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dosage")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("GenericName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(38, 2)
                        .HasColumnType("decimal(38,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SuppliedDate")
                        .HasColumnType("date");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("Medicines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandName = "",
                            Dosage = 0,
                            ExpiryDate = new DateOnly(1, 1, 1),
                            GenericName = "Paracetamol",
                            Price = 10.00m,
                            Quantity = 100,
                            ReorderLevel = 50,
                            SuppliedDate = new DateOnly(1, 1, 1),
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 2,
                            BrandName = "",
                            Dosage = 0,
                            ExpiryDate = new DateOnly(1, 1, 1),
                            GenericName = "Aspirin",
                            Price = 5.00m,
                            Quantity = 50,
                            ReorderLevel = 75,
                            SuppliedDate = new DateOnly(1, 1, 1),
                            SupplierId = 2
                        });
                });

            modelBuilder.Entity("MSMS.Models.MedicineInventory.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Address 1",
                            ContactNumber = "1234567890",
                            Name = "Supplier 1"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Address 2",
                            ContactNumber = "0987654321",
                            Name = "Supplier 2"
                        });
                });

            modelBuilder.Entity("MSMS.Models.Notification.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReferenceType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateOnly(2024, 11, 20),
                            Message = "Hello, World!",
                            ReferenceType = 0,
                            Title = "",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("MSMS.Models.Procedures.ActiveProcedure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("ProcedureId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProcedureServiceDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProcedureId");

                    b.ToTable("ActiveProcedures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PatientId = 1,
                            ProcedureId = 1,
                            ProcedureServiceDateTime = new DateTime(2024, 11, 20, 14, 32, 44, 775, DateTimeKind.Local).AddTicks(3932)
                        },
                        new
                        {
                            Id = 2,
                            PatientId = 2,
                            ProcedureId = 1,
                            ProcedureServiceDateTime = new DateTime(2024, 11, 19, 14, 32, 44, 775, DateTimeKind.Local).AddTicks(3934)
                        });
                });

            modelBuilder.Entity("MSMS.Models.Procedures.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactNumber = "1234567890",
                            FirstName = "John",
                            LastName = "Smith",
                            MiddleName = "Doe"
                        },
                        new
                        {
                            Id = 2,
                            ContactNumber = "0987654321",
                            FirstName = "Jane",
                            LastName = "Smith",
                            MiddleName = "Doe"
                        });
                });

            modelBuilder.Entity("MSMS.Models.Procedures.Procedure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ProcedureDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcedureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcedureNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProcedurePrice")
                        .HasPrecision(38, 2)
                        .HasColumnType("decimal(38,2)");

                    b.HasKey("Id");

                    b.ToTable("Procedure");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProcedureDescription = "Blood Test Duh",
                            ProcedureName = "Blood Test",
                            ProcedureNotes = "Disposable Syringe",
                            ProcedurePrice = 100.00m
                        },
                        new
                        {
                            Id = 2,
                            ProcedureDescription = "Analyze patient urine for bacteria or unbalanced electrolyte level.",
                            ProcedureName = "Urinalysis",
                            ProcedureNotes = "Make Patient drink water till they excrete.",
                            ProcedurePrice = 100.00m
                        });
                });

            modelBuilder.Entity("MSMS.Models.MedicineInventory.Medicine", b =>
                {
                    b.HasOne("MSMS.Models.MedicineInventory.Supplier", "Supplier")
                        .WithMany("Medicines")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MSMS.Models.Notification.Notification", b =>
                {
                    b.HasOne("MSMS.Models.Dashboard.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MSMS.Models.Procedures.ActiveProcedure", b =>
                {
                    b.HasOne("MSMS.Models.Procedures.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MSMS.Models.Procedures.Procedure", "Procedure")
                        .WithMany()
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Procedure");
                });

            modelBuilder.Entity("MSMS.Models.MedicineInventory.Supplier", b =>
                {
                    b.Navigation("Medicines");
                });
#pragma warning restore 612, 618
        }
    }
}
